COUNTRIES_EN_CH_DICT = {
    "Somalia": "索马里",
    "Liechtenstein": "列支敦士登",
    "Morocco": "摩洛哥",
    "W. Sahara": "西撒哈拉",
    "Serbia": "塞尔维亚",
    "Afghanistan": "阿富汗",
    "Angola": "安哥拉",
    "Albania": "阿尔巴尼亚",
    "Andorra": "安道尔共和国",
    "United Arab Emirates": "阿拉伯联合酋长国",
    "Argentina": "阿根廷",
    "Armenia": "亚美尼亚",
    "Australia": "澳大利亚",
    "Austria": "奥地利",
    "Azerbaijan": "阿塞拜疆",
    "Burundi": "布隆迪",
    "Belgium": "比利时",
    "Benin": "贝宁",
    "Burkina Faso": "布基纳法索",
    "Bangladesh": "孟加拉国",
    "Bulgaria": "保加利亚",
    "Bahrain": "巴林",
    "Bahamas": "巴哈马",
    "Bosnia and Herz.": "波斯尼亚和黑塞哥维那",
    "Belarus": "白俄罗斯",
    "Belize": "伯利兹",
    "Bermuda": "百慕大",
    "Bolivia": "玻利维亚",
    "Brazil": "巴西",
    "Barbados": "巴巴多斯",
    "Brunei": "文莱",
    "Bhutan": "不丹",
    "Botswana": "博茨瓦纳",
    "Central African Rep.": "中非",
    "Canada": "加拿大",
    "Switzerland": "瑞士",
    "Chile": "智利",
    "China": "中国",
    "Côte dIvoire": "科特迪瓦",
    "Cameroon": "喀麦隆",
    "Dem. Rep. Congo": "刚果民主共和国",
    "Congo": "刚果",
    "Colombia": "哥伦比亚",
    "Cape Verde": "佛得角",
    "Costa Rica": "哥斯达黎加",
    "Cuba": "古巴",
    "N. Cyprus": "北塞浦路斯",
    "Cyprus": "塞浦路斯",
    "Czech Rep.": "捷克",
    "Germany": "德国",
    "Djibouti": "吉布提",
    "Denmark": "丹麦",
    "Dominican Rep.": "多米尼加",
    "Algeria": "阿尔及利亚",
    "Ecuador": "厄瓜多尔",
    "Egypt": "埃及",
    "Eritrea": "厄立特里亚",
    "Spain": "西班牙",
    "Estonia": "爱沙尼亚",
    "Ethiopia": "埃塞俄比亚",
    "Finland": "芬兰",
    "Fiji": "斐济",
    "France": "法国",
    "Gabon": "加蓬",
    "United Kingdom": "英国",
    "Georgia": "格鲁吉亚",
    "Ghana": "加纳",
    "Guinea": "几内亚",
    "Gambia": "冈比亚",
    "Guinea-Bissau": "几内亚比绍",
    "Eq. Guinea": "赤道几内亚",
    "Greece": "希腊",
    "Grenada": "格林纳达",
    "Greenland": "格陵兰",
    "Guatemala": "危地马拉",
    "Guam": "关岛",
    "Guyana": "圭亚那",
    "Honduras": "洪都拉斯",
    "Croatia": "克罗地亚",
    "Haiti": "海地",
    "Hungary": "匈牙利",
    "Indonesia": "印度尼西亚",
    "India": "印度",
    "Br. Indian Ocean Ter.": "英属印度洋领土",
    "Ireland": "爱尔兰",
    "Iran": "伊朗",
    "Iraq": "伊拉克",
    "Iceland": "冰岛",
    "Israel": "以色列",
    "Italy": "意大利",
    "Jamaica": "牙买加",
    "Jordan": "约旦",
    "Japan": "日本",
    "Siachen Glacier": "锡亚琴冰川",
    "Kazakhstan": "哈萨克斯坦",
    "Kenya": "肯尼亚",
    "Kyrgyzstan": "吉尔吉斯坦",
    "Cambodia": "柬埔寨",
    "Korea": "韩国",
    "Kuwait": "科威特",
    "Lao PDR": "老挝",
    "Lebanon": "黎巴嫩",
    "Liberia": "利比里亚",
    "Libya": "利比亚",
    "Sri Lanka": "斯里兰卡",
    "Lesotho": "莱索托",
    "Lithuania": "立陶宛",
    "Luxembourg": "卢森堡",
    "Latvia": "拉脱维亚",
    "Moldova": "摩尔多瓦",
    "Madagascar": "马达加斯加",
    "Mexico": "墨西哥",
    "Macedonia": "马其顿",
    "Mali": "马里",
    "Malta": "马耳他",
    "Myanmar": "缅甸",
    "Montenegro": "黑山",
    "Mongolia": "蒙古",
    "Mozambique": "莫桑比克",
    "Mauritania": "毛里塔尼亚",
    "Mauritius": "毛里求斯",
    "Malawi": "马拉维",
    "Malaysia": "马来西亚",
    "Namibia": "纳米比亚",
    "New Caledonia": "新喀里多尼亚",
    "Niger": "尼日尔",
    "Nigeria": "尼日利亚",
    "Nicaragua": "尼加拉瓜",
    "Netherlands": "荷兰",
    "Norway": "挪威",
    "Nepal": "尼泊尔",
    "New Zealand": "新西兰",
    "Oman": "阿曼",
    "Pakistan": "巴基斯坦",
    "Panama": "巴拿马",
    "Peru": "秘鲁",
    "Philippines": "菲律宾",
    "Papua New Guinea": "巴布亚新几内亚",
    "Poland": "波兰",
    "Puerto Rico": "波多黎各",
    "Dem. Rep. Korea": "朝鲜",
    "Portugal": "葡萄牙",
    "Paraguay": "巴拉圭",
    "Palestine": "巴勒斯坦",
    "Qatar": "卡塔尔",
    "Romania": "罗马尼亚",
    "Russia": "俄罗斯",
    "Rwanda": "卢旺达",
    "Saudi Arabia": "沙特阿拉伯",
    "Sudan": "苏丹",
    "S. Sudan": "南苏丹",
    "Senegal": "塞内加尔",
    "Singapore": "新加坡",
    "Solomon Is.": "所罗门群岛",
    "Sierra Leone": "塞拉利昂",
    "El Salvador": "萨尔瓦多",
    "Suriname": "苏里南",
    "Slovakia": "斯洛伐克",
    "Slovenia": "斯洛文尼亚",
    "Sweden": "瑞典",
    "Swaziland": "斯威士兰",
    "Seychelles": "塞舌尔",
    "Syria": "叙利亚",
    "Chad": "乍得",
    "Togo": "多哥",
    "Thailand": "泰国",
    "Tajikistan": "塔吉克斯坦",
    "Turkmenistan": "土库曼斯坦",
    "Timor-Leste": "东帝汶",
    "Tonga": "汤加",
    "Trinidad and Tobago": "特立尼达和多巴哥",
    "Tunisia": "突尼斯",
    "Turkey": "土耳其",
    "Tanzania": "坦桑尼亚",
    "Uganda": "乌干达",
    "Ukraine": "乌克兰",
    "Uruguay": "乌拉圭",
    "United States": "美国",
    "Uzbekistan": "乌兹别克斯坦",
    "Venezuela": "委内瑞拉",
    "Vietnam": "越南",
    "Vanuatu": "瓦努阿图",
    "Yemen": "也门",
    "South Africa": "南非",
    "Zambia": "赞比亚",
    "Zimbabwe": "津巴布韦",
    "Aland": "奥兰群岛",
    "American Samoa": "美属萨摩亚",
    "Fr. S. Antarctic Lands": "南极洲",
    "Antigua and Barb.": "安提瓜和巴布达",
    "Comoros": "科摩罗",
    "Curaçao": "库拉索岛",
    "Cayman Is.": "开曼群岛",
    "Dominica": "多米尼加",
    "Falkland Is.": "马尔维纳斯群岛（福克兰）",
    "Faeroe Is.": "法罗群岛",
    "Micronesia": "密克罗尼西亚",
    "Heard I. and McDonald Is.": "赫德岛和麦克唐纳群岛",
    "Isle of Man": "曼岛",
    "Jersey": "泽西岛",
    "Kiribati": "基里巴斯",
    "Saint Lucia": "圣卢西亚",
    "N. Mariana Is.": "北马里亚纳群岛",
    "Montserrat": "蒙特塞拉特",
    "Niue": "纽埃",
    "Palau": "帕劳",
    "Fr. Polynesia": "法属波利尼西亚",
    "S. Geo. and S. Sandw. Is.": "南乔治亚岛和南桑威奇群岛",
    "Saint Helena": "圣赫勒拿",
    "St. Pierre and Miquelon": "圣皮埃尔和密克隆群岛",
    "São Tomé and Principe": "圣多美和普林西比",
    "Turks and Caicos Is.": "特克斯和凯科斯群岛",
    "St. Vin. and Gren.": "圣文森特和格林纳丁斯",
    "U.S. Virgin Is.": "美属维尔京群岛",
    "Samoa": "萨摩亚"
}
# 中文-英文字典
COUNTRIES_CH_EN_DICT = {
    "索马里": "Somalia",
    "列支敦士登": "Liechtenstein",
    "摩洛哥": "Morocco",
    "西撒哈拉": "W. Sahara",
    "塞尔维亚": "Serbia",
    "阿富汗": "Afghanistan",
    "安哥拉": "Angola",
    "阿尔巴尼亚": "Albania",
    "安道尔共和国": "Andorra",
    "阿拉伯联合酋长国": "United Arab Emirates",
    "阿根廷": "Argentina",
    "亚美尼亚": "Armenia",
    "澳大利亚": "Australia",
    "奥地利": "Austria",
    "阿塞拜疆": "Azerbaijan",
    "布隆迪": "Burundi",
    "比利时": "Belgium",
    "贝宁": "Benin",
    "布基纳法索": "Burkina Faso",
    "孟加拉国": "Bangladesh",
    "保加利亚": "Bulgaria",
    "巴林": "Bahrain",
    "巴哈马": "Bahamas",
    "波斯尼亚和黑塞哥维那": "Bosnia and Herz.",
    "白俄罗斯": "Belarus",
    "伯利兹": "Belize",
    "百慕大": "Bermuda",
    "玻利维亚": "Bolivia",
    "巴西": "Brazil",
    "巴巴多斯": "Barbados",
    "文莱": "Brunei",
    "不丹": "Bhutan",
    "博茨瓦纳": "Botswana",
    "中非": "Central African Rep.",
    "加拿大": "Canada",
    "瑞士": "Switzerland",
    "智利": "Chile",
    "中国": "China",
    "科特迪瓦": "Côte dIvoire",
    "喀麦隆": "Cameroon",
    "刚果民主共和国": "Dem. Rep. Congo",
    "刚果": "Congo",
    "哥伦比亚": "Colombia",
    "佛得角": "Cape Verde",
    "哥斯达黎加": "Costa Rica",
    "古巴": "Cuba",
    "北塞浦路斯": "N. Cyprus",
    "塞浦路斯": "Cyprus",
    "捷克": "Czech Rep.",
    "德国": "Germany",
    "吉布提": "Djibouti",
    "丹麦": "Denmark",
    "多米尼加": "Dominica",
    "阿尔及利亚": "Algeria",
    "厄瓜多尔": "Ecuador",
    "埃及": "Egypt",
    "厄立特里亚": "Eritrea",
    "西班牙": "Spain",
    "爱沙尼亚": "Estonia",
    "埃塞俄比亚": "Ethiopia",
    "芬兰": "Finland",
    "斐济": "Fiji",
    "法国": "France",
    "加蓬": "Gabon",
    "英国": "United Kingdom",
    "格鲁吉亚": "Georgia",
    "加纳": "Ghana",
    "几内亚": "Guinea",
    "冈比亚": "Gambia",
    "几内亚比绍": "Guinea-Bissau",
    "赤道几内亚": "Eq. Guinea",
    "希腊": "Greece",
    "格林纳达": "Grenada",
    "格陵兰": "Greenland",
    "危地马拉": "Guatemala",
    "关岛": "Guam",
    "圭亚那": "Guyana",
    "洪都拉斯": "Honduras",
    "克罗地亚": "Croatia",
    "海地": "Haiti",
    "匈牙利": "Hungary",
    "印度尼西亚": "Indonesia",
    "印度": "India",
    "英属印度洋领土": "Br. Indian Ocean Ter.",
    "爱尔兰": "Ireland",
    "伊朗": "Iran",
    "伊拉克": "Iraq",
    "冰岛": "Iceland",
    "以色列": "Israel",
    "意大利": "Italy",
    "牙买加": "Jamaica",
    "约旦": "Jordan",
    "日本": "Japan",
    "锡亚琴冰川": "Siachen Glacier",
    "哈萨克斯坦": "Kazakhstan",
    "肯尼亚": "Kenya",
    "吉尔吉斯坦": "Kyrgyzstan",
    "柬埔寨": "Cambodia",
    "韩国": "Korea",
    "科威特": "Kuwait",
    "老挝": "Lao PDR",
    "黎巴嫩": "Lebanon",
    "利比里亚": "Liberia",
    "利比亚": "Libya",
    "斯里兰卡": "Sri Lanka",
    "莱索托": "Lesotho",
    "立陶宛": "Lithuania",
    "卢森堡": "Luxembourg",
    "拉脱维亚": "Latvia",
    "摩尔多瓦": "Moldova",
    "马达加斯加": "Madagascar",
    "墨西哥": "Mexico",
    "马其顿": "Macedonia",
    "马里": "Mali",
    "马耳他": "Malta",
    "缅甸": "Myanmar",
    "黑山": "Montenegro",
    "蒙古": "Mongolia",
    "莫桑比克": "Mozambique",
    "毛里塔尼亚": "Mauritania",
    "毛里求斯": "Mauritius",
    "马拉维": "Malawi",
    "马来西亚": "Malaysia",
    "纳米比亚": "Namibia",
    "新喀里多尼亚": "New Caledonia",
    "尼日尔": "Niger",
    "尼日利亚": "Nigeria",
    "尼加拉瓜": "Nicaragua",
    "荷兰": "Netherlands",
    "挪威": "Norway",
    "尼泊尔": "Nepal",
    "新西兰": "New Zealand",
    "阿曼": "Oman",
    "巴基斯坦": "Pakistan",
    "巴拿马": "Panama",
    "秘鲁": "Peru",
    "菲律宾": "Philippines",
    "巴布亚新几内亚": "Papua New Guinea",
    "波兰": "Poland",
    "波多黎各": "Puerto Rico",
    "朝鲜": "Dem. Rep. Korea",
    "葡萄牙": "Portugal",
    "巴拉圭": "Paraguay",
    "巴勒斯坦": "Palestine",
    "卡塔尔": "Qatar",
    "罗马尼亚": "Romania",
    "俄罗斯": "Russia",
    "卢旺达": "Rwanda",
    "沙特阿拉伯": "Saudi Arabia",
    "苏丹": "Sudan",
    "南苏丹": "S. Sudan",
    "塞内加尔": "Senegal",
    "新加坡": "Singapore",
    "所罗门群岛": "Solomon Is.",
    "塞拉利昂": "Sierra Leone",
    "萨尔瓦多": "El Salvador",
    "苏里南": "Suriname",
    "斯洛伐克": "Slovakia",
    "斯洛文尼亚": "Slovenia",
    "瑞典": "Sweden",
    "斯威士兰": "Swaziland",
    "塞舌尔": "Seychelles",
    "叙利亚": "Syria",
    "乍得": "Chad",
    "多哥": "Togo",
    "泰国": "Thailand",
    "塔吉克斯坦": "Tajikistan",
    "土库曼斯坦": "Turkmenistan",
    "东帝汶": "Timor-Leste",
    "汤加": "Tonga",
    "特立尼达和多巴哥": "Trinidad and Tobago",
    "突尼斯": "Tunisia",
    "土耳其": "Turkey",
    "坦桑尼亚": "Tanzania",
    "乌干达": "Uganda",
    "乌克兰": "Ukraine",
    "乌拉圭": "Uruguay",
    "美国": "United States",
    "乌兹别克斯坦": "Uzbekistan",
    "委内瑞拉": "Venezuela",
    "越南": "Vietnam",
    "瓦努阿图": "Vanuatu",
    "也门": "Yemen",
    "南非": "South Africa",
    "赞比亚": "Zambia",
    "津巴布韦": "Zimbabwe",
    "奥兰群岛": "Aland",
    "美属萨摩亚": "American Samoa",
    "南极洲": "Fr. S. Antarctic Lands",
    "安提瓜和巴布达": "Antigua and Barb.",
    "科摩罗": "Comoros",
    "库拉索岛": "Curaçao",
    "开曼群岛": "Cayman Is.",
    "马尔维纳斯群岛（福克兰）": "Falkland Is.",
    "法罗群岛": "Faeroe Is.",
    "密克罗尼西亚": "Micronesia",
    "赫德岛和麦克唐纳群岛": "Heard I. and McDonald Is.",
    "曼岛": "Isle of Man",
    "泽西岛": "Jersey",
    "基里巴斯": "Kiribati",
    "圣卢西亚": "Saint Lucia",
    "北马里亚纳群岛": "N. Mariana Is.",
    "蒙特塞拉特": "Montserrat",
    "纽埃": "Niue",
    "帕劳": "Palau",
    "法属波利尼西亚": "Fr. Polynesia",
    "南乔治亚岛和南桑威奇群岛": "S. Geo. and S. Sandw. Is.",
    "圣赫勒拿": "Saint Helena",
    "圣皮埃尔和密克隆群岛": "St. Pierre and Miquelon",
    "圣多美和普林西比": "São Tomé and Principe",
    "特克斯和凯科斯群岛": "Turks and Caicos Is.",
    "圣文森特和格林纳丁斯": "St. Vin. and Gren.",
    "美属维尔京群岛": "U.S. Virgin Is.",
    "萨摩亚": "Samoa"
}
